In [3]:
import numpy as np

In [5]:
array = np.array([1,2,3,4])

In [7]:
print (array)

[1 2 3 4]


In [9]:
arr = np.arange(1,20,4)


In [11]:
print(arr)

[ 1  5  9 13 17]


In [13]:
arr = np.arange(1,5)

In [15]:
print(arr)

[1 2 3 4]


In [17]:
arr = np.arange(3,67,8)

In [19]:
print(arr)

[ 3 11 19 27 35 43 51 59]


In [21]:
arr = np.linspace(1.5,5,10)
print(arr)

[1.5        1.88888889 2.27777778 2.66666667 3.05555556 3.44444444
 3.83333333 4.22222222 4.61111111 5.        ]


In [23]:
arr = np.linspace(2,10,20)
print(arr)

[ 2.          2.42105263  2.84210526  3.26315789  3.68421053  4.10526316
  4.52631579  4.94736842  5.36842105  5.78947368  6.21052632  6.63157895
  7.05263158  7.47368421  7.89473684  8.31578947  8.73684211  9.15789474
  9.57894737 10.        ]


In [25]:
arr = np.linspace(5,45,67)
print(arr)

[ 5.          5.60606061  6.21212121  6.81818182  7.42424242  8.03030303
  8.63636364  9.24242424  9.84848485 10.45454545 11.06060606 11.66666667
 12.27272727 12.87878788 13.48484848 14.09090909 14.6969697  15.3030303
 15.90909091 16.51515152 17.12121212 17.72727273 18.33333333 18.93939394
 19.54545455 20.15151515 20.75757576 21.36363636 21.96969697 22.57575758
 23.18181818 23.78787879 24.39393939 25.         25.60606061 26.21212121
 26.81818182 27.42424242 28.03030303 28.63636364 29.24242424 29.84848485
 30.45454545 31.06060606 31.66666667 32.27272727 32.87878788 33.48484848
 34.09090909 34.6969697  35.3030303  35.90909091 36.51515152 37.12121212
 37.72727273 38.33333333 38.93939394 39.54545455 40.15151515 40.75757576
 41.36363636 41.96969697 42.57575758 43.18181818 43.78787879 44.39393939
 45.        ]


In [29]:
arr = np.array([23,45,66,98])
print(arr)

[23 45 66 98]


In [31]:
# 0 dimension 

In [33]:
arr = np.array(23)
print(arr)

23


In [35]:
arr = np.array([23,56,78,89])
print(arr)

[23 56 78 89]


In [39]:
arr = np.array([23,56,87,23])
print(arr)
print("dimension:" ,np.ndim(arr))

[23 56 87 23]
dimension: 1


In [47]:
arr = np.array([[23,54],[65,67],[23,98]])
print(arr)
print("dimension:" ,np.ndim(arr))
# 2 dimension array

[[23 54]
 [65 67]
 [23 98]]
dimension: 2


In [55]:
arr = np.array([[12,45],[32,78],[67,34],[89,45],[87,56],[23,98]])
print(arr)
print("dimension:",np.ndim(arr))

[[12 45]
 [32 78]
 [67 34]
 [89 45]
 [87 56]
 [23 98]]
dimension: 2


In [59]:
arr = np.array([23,45])
print(arr)
print("dimension:",np.ndim(arr))
print("shape:",np.shape(arr))

[23 45]
dimension: 1
shape: (2,)


In [61]:
arr = np.array([[34,65],[56,87]])
print(arr)
print("dimension:",np.ndim(arr))
print("shape:",np.shape(arr))

[[34 65]
 [56 87]]
dimension: 2
shape: (2, 2)


In [63]:
arr = np.array([23,45,76,98,45])
print(arr[3])

98


In [67]:
arr =  np.array([12,45,6,76])
print(arr[-3])
# one dimension array

45


In [77]:
# two dimension array
arr = np.array([[19,56575,543,64],[34,66,865,334]])
print(arr[1][2])

865


In [81]:
print(arr[0][3])

64


In [89]:
# multiplication method
arr = np.array([12,445,66,76])
print(arr)

[ 12 445  66  76]


In [91]:
print(arr*3)

[  36 1335  198  228]


In [93]:
print(arr*7)

[  84 3115  462  532]


In [97]:
arr = np.array([[12,4,354],[23,76,98]])
print(arr*3)

[[  36   12 1062]
 [  69  228  294]]


In [99]:
arr = np.array([1,45,67,34,76])
str1 = "aman"
for i in str1:
    print(i)

a
m
a
n


In [101]:
arr = np.array([2,56,87,45])
str1 = "aman"
for i in arr:
    print(i)

2
56
87
45


In [103]:
arr = np.array([[12,45,76],[34,87,67]])
for i in arr:
    for j in i:
        print(j)

12
45
76
34
87
67


In [107]:
import numpy

In [113]:
arr = numpy.array([[12,56],[34,87]])
for a in range(0,numpy.size(arr)):
    print(a)


0
1
2
3


In [115]:
arr = numpy.array([[12,56,46],[56,88,67]])
for a in range(0,2):
    for b in range(0,2):
        print(arr[a][b])

12
56
56
88


In [117]:
# addition method

In [119]:
arr1=numpy.array([[12,56,46],[56,88,67]])
arr2=numpy.array([[12,5,46],[58,88,65]])
for a in range(0,2):
    for b in range(0,3):
        print(arr1[a][b]+arr2[a][b])

24
61
92
114
176
132


In [121]:
# write a program to traverse a matrix

In [127]:
arr = numpy.array([[12,56,46],[56,88,67]])
print(arr)


[[12 56 46]
 [56 88 67]]


In [135]:
arr = numpy.array([[12,56,46],[56,88,67]])
print(arr)
for a in range (0,2):
    for b in range (0,3):
        print([a],[b])

[[12 56 46]
 [56 88 67]]
[0] [0]
[0] [1]
[0] [2]
[1] [0]
[1] [1]
[1] [2]


In [141]:
import numpy as np
arr1 = np.array([2,5,67])
arr2 = arr1.copy()
arr1[2]=9
print(arr1)


[2 5 9]


In [151]:
import numpy as np
arr1 = np.array([2,34564,56,678,56])
target = 7 
for a in range(0,np.size(arr1)):
    if (arr1[a]==target):
        print("value Found on position:",a)
    

In [153]:
import numpy as np 
arr1 = np.array([2,34564,56,678,56])
arr = np.zeros_like(arr1)
print(arr)
# array creation functions

[0 0 0 0 0]


In [155]:
import numpy as np
arr1  = np.array([2,34564,56,678,56])
arr = np.ones_like(arr1)
print(arr)

[1 1 1 1 1]


In [157]:
import numpy as np
arr1  = np.array([2,34564,56,678,56])
arr = np.eye(4,dtype=int)
print(arr)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [161]:
# array manipulation function
# reshape:- to change the shape of an array

In [177]:
arr = np.array([[2,345,56],[22,76,54]])
print(arr)
arr1 = np.reshape(arr(56,0))
print(arr1)


[[  2 345  56]
 [ 22  76  54]]


TypeError: 'numpy.ndarray' object is not callable

In [175]:
import numpy as np
arr = np.array([[2,34,56],[6,56,34]])
print(arr)
arr1 = np.transpose(arr)
print(arr1)

[[ 2 34 56]
 [ 6 56 34]]
[[ 2  6]
 [34 56]
 [56 34]]


In [179]:
# array mathematical function
import numpy as np
arr1 =np.array([12,55])
arr2 =np.array([34,67])
arr3 =np.add(arr1,arr2)
print(arr3)

[ 46 122]


In [183]:
import numpy as np
arr1 = np.array([14,76])
arr2 =np.array([34,67])
arr3 =np.subtract(arr2,arr1)
print(arr3)

[20 -9]


In [185]:
import numpy as np
arr1 = np.array([14,76])
arr3 =np.sqrt(arr1)
print(arr3)

[3.74165739 8.71779789]


In [189]:
import numpy as np
arr1 = np.array([14,76])
arr3 =np.power(arr1,2)
print(arr3)

[ 196 5776]


In [193]:
# array stats functions
marks=np.array([223,56,87])
print("median:" ,np.median(marks))

median: 87.0


In [199]:
marks=np.array([223,56,87])
print("mean:" ,np.mean(marks))



mean: 122.0
